"""Incremental, forkable CAVLC macroblock automaton for constrained decoding.

The parser in ``h264_syntax.py`` reads whole syntax elements per call and cannot
be paused between bits, so it can only answer "is this byte legal?" by re-parsing
the whole NAL per candidate -- O(256 x NAL) per generated byte. This module is the
steppable equivalent: a state machine over RBSP *bits* that consumes one bit at a
time (``consume_bit``), can be cheaply cloned to explore alternatives, and reaches
``COMPLETE_MB``/``DONE`` structurally (no RBSP-length dependence). From it we
compile a 256-byte legal-continuation mask without replaying the NAL prefix.

Scope: Constrained Baseline, CAVLC, P/I slices (the corpus we generate). It decodes
the *entire* MB (mb_skip_run -> mb_type -> prediction -> cbp -> mb_qp_delta ->
residual) because reaching residual with correct nC/cbp context requires consuming
every prior field. Fields whose legal set is bounded (mb_type, sub_mb_type, ref_idx,
intra_chroma_pred_mode, cbp, and 8-bit mb_qp_delta) are pruned while decoding.
Motion-vector differences accept every successfully decoded se(v); their derived
level-dependent range is outside this slice-data automaton.
I_PCM is handled as raw bytes. B-slices / non-CAVLC are out of scope.

Stdlib-only (imports only ``h264_cavlc_tables``) so tests load it by path.

Mirrors, bit-for-bit: ``_residual_block`` / ``_parse_residual`` / ``_parse_macroblock``
/ ``_parse_inter_pred`` / ``_NNZ`` in ``h264_syntax.py``.
"""

from __future__ import annotations

try:  # package import (full env) vs flat import (stdlib-only tests)
    from . import h264_cavlc_tables as T
except ImportError:  # pragma: no cover
    import h264_cavlc_tables as T

# --- status codes returned by consume_bit ----------------------------------
MORE = "more"  # element not finished; keep feeding bits
COMPLETE_MB = "complete_mb"  # a macroblock just finished (more may follow)
DONE = "done"  # rbsp_trailing_bits consumed -> NAL fully parsed
INVALID = "invalid"  # this bit makes the stream un-decodable

_RESIDUAL_TAGS = {
    "coeff_token",
    "signs",
    "level_prefix",
    "level_suffix",
    "total_zeros",
    "run_before",
}

# P macroblock partition count: mb_type -> num_parts (mirror _P_MB).
_P_NUM_PARTS = {0: 1, 1: 2, 2: 2, 3: 4, 4: 4}
_SUB_MB_NUM_PARTS = {0: 1, 1: 2, 2: 2, 3: 4}  # P sub_mb_type -> sub-partitions
_BASELINE_MB_QP_DELTA_MIN = -26
_BASELINE_MB_QP_DELTA_MAX = 25


class MbAutomaton:
    """Bit-stepped decoder for the slice-data (macroblock) portion of one VCL NAL.

    Construct positioned at the first slice-data bit (``slice_data_start_bit``); the
    slice header is parsed elsewhere and its context (slice_type, num_ref, dims) is
    passed in. Feed RBSP bits with ``consume_bit``. Clone to fork.
    """

    def __init__(
        self,
        *,
        pic_width_in_mbs: int,
        pic_height_in_mbs: int,
        slice_type: int,
        num_ref_idx_l0_active: int,
        first_mb_in_slice: int,
        slice_data_start_bit: int,
        max_mbs: int,
    ) -> None:
        picture_mbs = pic_width_in_mbs * pic_height_in_mbs
        if pic_width_in_mbs <= 0 or pic_height_in_mbs <= 0:
            raise ValueError("picture dimensions must be positive")
        if not 0 <= first_mb_in_slice < picture_mbs:
            raise ValueError("first_mb_in_slice outside picture")
        if max_mbs <= 0 or first_mb_in_slice + max_mbs > picture_mbs:
            raise ValueError("max_mbs exceeds remaining picture macroblocks")
        self.W = pic_width_in_mbs
        self.H = pic_height_in_mbs
        self.is_p = (slice_type % 5) == 0
        self.num_ref = num_ref_idx_l0_active
        self.first_mb = first_mb_in_slice
        self.max_mbs = max_mbs
        self.pos = slice_data_start_bit  # absolute RBSP bit index of the NEXT bit

        # Picture-level nnz grids (nC neighbour prediction), -1 == unavailable.
        self.luma = [[-1] * (self.W * 4) for _ in range(self.H * 4)]
        self.chroma = [
            [[-1] * (self.W * 2) for _ in range(self.H * 2)] for _ in range(2)
        ]
        # Copy-on-write overlay used during compile_byte_mask lookahead; None in the
        # committed state (writes then go straight to the grids above).
        self.overlay = None  # type: dict | None

        self.mbs_done = 0
        self.stage = "slice"  # "slice" | "trailing" | "done"
        self.seen_stop = False

        # Active variable-length element being read.
        self.ae_kind = None  # "ue"|"se"|"te"|"u"|"vlc"|"unary"|None
        self.ae_tag = None
        self.ae_bits = ""
        self.ae_n = 0
        self.ae_label = ""
        self.ae_xmax = 0

        # Per-MB context.
        self.cur_mbx = 0
        self.cur_mby = 0
        self.mb_type = 0
        self.inter = False
        self.intra16x16 = False
        self.mb_mode = ""  # "I_NxN"|"I_16x16"|"I_PCM"
        self.cbp_luma = 0
        self.cbp_chroma = 0
        self.i16_pred_cbp = None
        self.pred_blk = 0
        self.ip_sub = []  # sub_mb_type values (mb_type 3/4)
        self.ip_queue = []  # remaining inter-pred reads: ("ref", xmax) | ("mvd",)

        # Residual position + block-persistent locals.
        self.res_phase = ""
        self.res_blk = 0
        self.res_comp = 0
        self.cur_set = None  # nnz write target for the block being read
        self.rb_max = 0
        self.rb_nc = 0
        self.rb_total_coeff = 0
        self.rb_trailing_ones = 0
        self.rb_suffix_length = 0
        self.rb_i = 0
        self.rb_level_prefix = 0
        self.rb_suffix_size = 0
        self.rb_total_zeros = 0
        self.rb_zeros_left = 0
        self.rb_run_i = 0

        self._begin_slice()

    # -- cloning (cheap: scalars + small lists/overlay; grids shared) --------
    def clone(self) -> "MbAutomaton":
        c = MbAutomaton.__new__(MbAutomaton)
        c.__dict__.update(self.__dict__)
        # Grids are shared read-only during lookahead; overlay/lists are per-branch.
        c.overlay = None if self.overlay is None else dict(self.overlay)
        c.ip_sub = list(self.ip_sub)
        c.ip_queue = list(self.ip_queue)
        return c

    # -- nnz grid access (overlay-aware) ------------------------------------
    @staticmethod
    def _luma_coords(mbx, mby, blk):
        q, r = blk >> 2, blk & 3
        return mbx * 4 + (q & 1) * 2 + (r & 1), mby * 4 + (q >> 1) * 2 + (r >> 1)

    @staticmethod
    def _chroma_coords(mbx, mby, blk):
        return mbx * 2 + (blk & 1), mby * 2 + (blk >> 1)

    def _cell_luma(self, x, y):
        if x < 0 or y < 0:
            return -1
        if self.overlay is not None:
            v = self.overlay.get(("L", x, y))
            if v is not None:
                return v
        return self.luma[y][x]

    def _cell_chroma(self, comp, x, y):
        if x < 0 or y < 0:
            return -1
        if self.overlay is not None:
            v = self.overlay.get(("C", comp, x, y))
            if v is not None:
                return v
        return self.chroma[comp][y][x]

    @staticmethod
    def _predict(n_a, n_b):
        avail_a, avail_b = n_a >= 0, n_b >= 0
        if avail_a and avail_b:
            return (n_a + n_b + 1) >> 1
        if avail_a:
            return n_a
        if avail_b:
            return n_b
        return 0

    def _predict_luma(self, blk):
        x, y = self._luma_coords(self.cur_mbx, self.cur_mby, blk)
        return self._predict(self._cell_luma(x - 1, y), self._cell_luma(x, y - 1))

    def _predict_chroma(self, comp, blk):
        x, y = self._chroma_coords(self.cur_mbx, self.cur_mby, blk)
        return self._predict(
            self._cell_chroma(comp, x - 1, y), self._cell_chroma(comp, x, y - 1)
        )

    def _set_luma(self, mbx, mby, blk, val):
        x, y = self._luma_coords(mbx, mby, blk)
        if self.overlay is not None:
            self.overlay[("L", x, y)] = val
        else:
            self.luma[y][x] = val

    def _set_chroma(self, mbx, mby, comp, blk, val):
        x, y = self._chroma_coords(mbx, mby, blk)
        if self.overlay is not None:
            self.overlay[("C", comp, x, y)] = val
        else:
            self.chroma[comp][y][x] = val

    def _set_mb(self, mbx, mby, luma_val, chroma_val):
        for b in range(16):
            self._set_luma(mbx, mby, b, luma_val)
        for c in range(2):
            for b in range(4):
                self._set_chroma(mbx, mby, c, b, chroma_val)

    # -- element start + incremental decode ---------------------------------
    def _start(self, kind, tag, *, n=0, label="", xmax=0):
        self.ae_kind = kind
        self.ae_tag = tag
        self.ae_bits = ""
        self.ae_n = n
        self.ae_label = label
        self.ae_xmax = xmax

    def _feed(self):
        """Feed self.ae_bits to the active element. Returns ('more',)/('done',v)/
        ('invalid',)."""
        s = self.ae_bits  # string of bits (0/1) for the active element
        k = self.ae_kind  # "u"|"ue"|"se"|"te"|"unary"|"vlc"
        if k == "u":
            if len(s) < self.ae_n:
                return ("more",)
            return ("done", int(s, 2) if s else 0)
        if k == "ue" or k == "se":
            r = _try_ue(s)
            if r[0] != "done":
                return r
            v = r[1]
            return ("done", _se(v) if k == "se" else v)
        if k == "te":
            if self.ae_xmax == 1:
                return ("done", 1 - int(s[-1]))  # exactly one bit
            r = _try_ue(s)
            if r[0] != "done":
                return r
            return ("done", r[1]) if r[1] <= self.ae_xmax else ("invalid",)
        if k == "unary":
            z = s.find("1")
            if z == -1:
                return ("invalid",) if len(s) > 60 else ("more",)
            return ("done", z)
        if k == "vlc":
            cmap = T.code_map(self.ae_label)
            if s in cmap:
                return ("done", cmap[s])
            for key in cmap:
                if key.startswith(s):
                    return ("more",)
            return ("invalid",)
        raise AssertionError(f"bad ae_kind {k!r}")

    def consume_bit(self, bit: int):
        # three stages: slice-data, trailing rbsp_trailing_bits, done. Each stage has its own
        self.pos += 1
        if self.stage == "trailing":
            return self._trailing_bit(bit)
        if self.stage == "done":
            return INVALID
        # slice stage: feed the bit to the active element and see if it completes.
        self.ae_bits += (
            "1" if bit else "0"
        )  # append bit to the active element's bit buffer. "ae" stands for "active element"
        r = self._feed()
        if r[0] == "more":
            return MORE
        if r[0] == "invalid":
            return INVALID
        return self._on_done(r[1])

    # -- trailing rbsp_trailing_bits (stop 1, then 0s to byte boundary) ------
    def _begin_trailing(self):
        self.stage = "trailing"
        self.seen_stop = False

    def _trailing_bit(self, bit):
        if not self.seen_stop:
            if bit != 1:
                return INVALID
            self.seen_stop = True
        else:
            if bit != 0:
                return INVALID
        if self.pos % 8 == 0:
            self.stage = "done"
            return DONE
        return MORE

    # -- slice / macroblock control flow ------------------------------------
    def _begin_slice(self):
        if self.is_p:
            self._start("ue", "mb_skip_run")
        else:
            self._begin_mb()

    def _begin_mb(self):
        addr = self.first_mb + self.mbs_done
        self.cur_mbx = addr % self.W
        self.cur_mby = addr // self.W
        self.inter = False
        self.intra16x16 = False
        self.mb_mode = ""
        self.i16_pred_cbp = None
        self._start("ue", "mb_type")

    def _finish_mb(self):
        self.mbs_done += 1
        if self.mbs_done >= self.max_mbs:
            self._begin_trailing()
        elif self.is_p:
            self._start("ue", "mb_skip_run")
        else:
            self._begin_mb()
        return COMPLETE_MB

    def _on_done(self, val):
        tag = self.ae_tag
        if tag == "mb_skip_run":
            return self._on_skip_run(val)
        if tag == "mb_type":
            return self._on_mb_type(val)
        if tag == "sub_mb_type":
            return self._on_sub_mb_type(val)
        if tag in ("ref_idx", "mvd"):
            return self._next_ip()
        if tag == "prev_intra":
            if val == 0:
                self._start("u", "rem_intra", n=3)
                return MORE
            return self._advance_pred_blk()
        if tag == "rem_intra":
            return self._advance_pred_blk()
        if tag == "intra_chroma":
            if not 0 <= val <= 3:
                return INVALID
            if self.mb_mode == "I_16x16":
                _, self.cbp_chroma, self.cbp_luma = self.i16_pred_cbp
                return self._residual_gate()
            self._start("ue", "cbp")
            return MORE
        if tag == "cbp":
            return self._on_cbp(val)
        if tag == "mb_qp_delta":
            if not _BASELINE_MB_QP_DELTA_MIN <= val <= _BASELINE_MB_QP_DELTA_MAX:
                return INVALID
            return self._res_begin()
        if tag == "pcm_align":
            if val != 0:
                return INVALID
            self._start("u", "pcm", n=(256 + 2 * 64) * 8)
            return MORE
        if tag == "pcm":
            self._set_mb(self.cur_mbx, self.cur_mby, 16, 16)
            return self._finish_mb()
        # residual sub-elements
        if tag == "coeff_token":
            return self._rb_coeff_token(val)
        if tag == "signs":
            return self._rb_start_levels()
        if tag == "level_prefix":
            return self._rb_level_prefix(val)
        if tag == "level_suffix":
            return self._rb_level_finish(val)
        if tag == "total_zeros":
            self.rb_total_zeros = val
            return self._rb_init_run_before()
        if tag == "run_before":
            self.rb_zeros_left -= val
            self.rb_run_i += 1
            return self._rb_run_next()
        raise AssertionError(f"bad tag {tag!r}")

    def _on_skip_run(self, run):
        remaining = self.max_mbs - self.mbs_done
        if run > remaining:
            return INVALID
        skipped = run
        for k in range(skipped):
            addr = self.first_mb + self.mbs_done + k
            self._set_mb(addr % self.W, addr // self.W, 0, 0)
        self.mbs_done += skipped
        if run == 0:
            self._begin_mb()
            return MORE
        if self.mbs_done >= self.max_mbs:
            self._begin_trailing()
            return COMPLETE_MB
        self._begin_mb()
        return MORE

    def _on_mb_type(self, mb_type):
        self.mb_type = mb_type
        if self.is_p and mb_type < 5:
            self.inter = True
            return self._begin_inter_pred()
        i_mb_type = mb_type - 5 if self.is_p else mb_type
        if i_mb_type == 0:
            self.mb_mode = "I_NxN"
            self.pred_blk = 0
            self._start("u", "prev_intra", n=1)
            return MORE
        if i_mb_type == 25:
            self.mb_mode = "I_PCM"
            align = (8 - self.pos % 8) % 8
            if align:
                self._start("u", "pcm_align", n=align)
            else:
                self._start("u", "pcm", n=(256 + 2 * 64) * 8)
            return MORE
        if 1 <= i_mb_type <= 24:
            self.mb_mode = "I_16x16"
            self.intra16x16 = True
            idx = i_mb_type - 1
            self.i16_pred_cbp = (idx % 4, (idx // 4) % 3, 15 if idx >= 12 else 0)
            self._start("ue", "intra_chroma")
            return MORE
        return INVALID  # bad intra mb_type (parser raises _DesyncError)

    # -- inter prediction ----------------------------------------------------
    def _begin_inter_pred(self):
        if self.mb_type in (3, 4):
            self.ip_sub = []
            self._start("ue", "sub_mb_type")
            return MORE
        num_parts = _P_NUM_PARTS[self.mb_type]
        self.ip_queue = []
        if self.num_ref > 1:
            self.ip_queue += [("ref", self.num_ref - 1)] * num_parts
        for _ in range(num_parts):
            self.ip_queue += [("mvd",), ("mvd",)]
        return self._next_ip()

    def _on_sub_mb_type(self, val):
        if val not in _SUB_MB_NUM_PARTS:
            return INVALID
        self.ip_sub.append(val)
        if len(self.ip_sub) < 4:
            self._start("ue", "sub_mb_type")
            return MORE
        self.ip_queue = []
        if self.mb_type == 3 and self.num_ref > 1:
            self.ip_queue += [("ref", self.num_ref - 1)] * 4
        for st in self.ip_sub:
            for _ in range(_SUB_MB_NUM_PARTS[st]):
                self.ip_queue += [("mvd",), ("mvd",)]
        return self._next_ip()

    def _next_ip(self):
        if not self.ip_queue:
            self._start("ue", "cbp")
            return MORE
        step = self.ip_queue.pop(0)
        if step[0] == "ref":
            self._start("te", "ref_idx", xmax=step[1])
        else:
            self._start("se", "mvd")
        return MORE

    def _advance_pred_blk(self):
        self.pred_blk += 1
        if self.pred_blk < 16:
            self._start("u", "prev_intra", n=1)
            return MORE
        self._start("ue", "intra_chroma")
        return MORE

    def _on_cbp(self, code_num):
        table = T.GOLOMB_TO_INTER_CBP if self.inter else T.GOLOMB_TO_INTRA_CBP
        if code_num < 0 or code_num >= len(table):
            return INVALID
        cbp = table[code_num]
        self.cbp_luma, self.cbp_chroma = cbp & 15, cbp >> 4
        return self._residual_gate()

    def _residual_gate(self):
        if self.cbp_luma > 0 or self.cbp_chroma > 0 or self.intra16x16:
            self._start("se", "mb_qp_delta")
            return MORE
        self._set_mb(self.cur_mbx, self.cur_mby, 0, 0)
        return self._finish_mb()

    # -- residual position machine ------------------------------------------
    def _res_begin(self):
        self.res_phase = "luma_dc" if self.intra16x16 else "luma"
        self.res_blk = 0
        self.res_comp = 0
        return self._res_next()

    def _res_next(self):
        while True:
            if self.res_phase == "luma_dc":
                nc = self._predict_luma(0)
                self.res_phase = "luma"
                self.res_blk = 0
                return self._rb_start(nc, 16, None)
            if self.res_phase == "luma":
                while self.res_blk < 16:
                    blk = self.res_blk
                    if self.cbp_luma & (1 << (blk >> 2)):
                        nc = self._predict_luma(blk)
                        maxc = 15 if self.intra16x16 else 16
                        self.res_blk += 1
                        return self._rb_start(nc, maxc, ("L", blk))
                    self._set_luma(self.cur_mbx, self.cur_mby, blk, 0)
                    self.res_blk += 1
                self.res_phase = "chroma_dc"
                self.res_comp = 0
                continue
            if self.res_phase == "chroma_dc":
                if self.cbp_chroma in (1, 2):
                    if self.res_comp < 2:
                        self.res_comp += 1
                        return self._rb_start(-1, 4, None)
                    self.res_phase = "chroma_ac"
                    self.res_comp = 0
                    self.res_blk = 0
                    continue
                for c in range(2):
                    for b in range(4):
                        self._set_chroma(self.cur_mbx, self.cur_mby, c, b, 0)
                return self._finish_mb()
            if self.res_phase == "chroma_ac":
                if self.cbp_chroma == 2:
                    while self.res_comp < 2:
                        if self.res_blk < 4:
                            comp, blk = self.res_comp, self.res_blk
                            nc = self._predict_chroma(comp, blk)
                            self.res_blk += 1
                            return self._rb_start(nc, 15, ("C", comp, blk))
                        self.res_comp += 1
                        self.res_blk = 0
                    return self._finish_mb()
                for c in range(2):
                    for b in range(4):
                        self._set_chroma(self.cur_mbx, self.cur_mby, c, b, 0)
                return self._finish_mb()
            raise AssertionError(f"bad res_phase {self.res_phase!r}")

    def _write_block_nnz(self, tc):
        t = self.cur_set
        if t is None:
            return
        if t[0] == "L":
            self._set_luma(self.cur_mbx, self.cur_mby, t[1], tc)
        else:
            self._set_chroma(self.cur_mbx, self.cur_mby, t[1], t[2], tc)

    # -- residual block (one CAVLC block) -----------------------------------
    def _rb_start(self, nc, max_coeff, set_target):
        self.cur_set = set_target
        self.rb_max = max_coeff
        self.rb_nc = nc
        self._start("vlc", "coeff_token", label=T.coeff_token_label(nc))
        return MORE

    def _rb_coeff_token(self, val):
        tc, t1 = val
        self.rb_total_coeff = tc
        self.rb_trailing_ones = t1
        if tc == 0:
            self._write_block_nnz(0)
            return self._res_next()
        if t1 > 0:
            self._start("u", "signs", n=t1)
            return MORE
        return self._rb_start_levels()

    def _rb_start_levels(self):
        tc, t1 = self.rb_total_coeff, self.rb_trailing_ones
        self.rb_suffix_length = 1 if (tc > 10 and t1 < 3) else 0
        self.rb_i = 0
        if tc == t1:
            return self._rb_start_total_zeros()
        self._start("unary", "level_prefix")
        return MORE

    def _rb_level_prefix(self, lp):
        self.rb_level_prefix = lp
        sl = self.rb_suffix_length
        if lp == 14 and sl == 0:
            ss = 4
        elif lp >= 15:
            ss = lp - 3
        else:
            ss = sl
        self.rb_suffix_size = ss
        if ss > 0:
            self._start("u", "level_suffix", n=ss)
            return MORE
        return self._rb_level_finish(0)

    def _rb_level_finish(self, level_suffix):
        lp = self.rb_level_prefix
        sl = self.rb_suffix_length
        level_code = (min(15, lp) << sl) + level_suffix
        if lp >= 15 and sl == 0:
            level_code += 15
        if lp >= 16:
            level_code += (1 << (lp - 3)) - 4096
        if self.rb_i == 0 and self.rb_trailing_ones < 3:
            level_code += 2
        level = (level_code + 2) >> 1 if level_code % 2 == 0 else (-level_code - 1) >> 1
        if self.rb_suffix_length == 0:
            self.rb_suffix_length = 1
        if (
            abs(level) > (3 << (self.rb_suffix_length - 1))
            and self.rb_suffix_length < 6
        ):
            self.rb_suffix_length += 1
        self.rb_i += 1
        if self.rb_i < self.rb_total_coeff - self.rb_trailing_ones:
            self._start("unary", "level_prefix")
            return MORE
        return self._rb_start_total_zeros()

    def _rb_start_total_zeros(self):
        if self.rb_total_coeff < self.rb_max:
            label = (
                f"total_zeros_cdc_{self.rb_total_coeff}"
                if self.rb_max == 4
                else f"total_zeros_4x4_{self.rb_total_coeff}"
            )
            self._start("vlc", "total_zeros", label=label)
            return MORE
        self.rb_total_zeros = 0
        return self._rb_init_run_before()

    def _rb_init_run_before(self):
        self.rb_zeros_left = self.rb_total_zeros
        self.rb_run_i = 0
        return self._rb_run_next()

    def _rb_run_next(self):
        if self.rb_run_i < self.rb_total_coeff - 1 and self.rb_zeros_left > 0:
            self._start(
                "vlc", "run_before", label=f"run_before_{min(self.rb_zeros_left, 7)}"
            )
            return MORE
        self._write_block_nnz(self.rb_total_coeff)
        return self._res_next()


# --- exp-Golomb helpers (incremental) --------------------------------------
def _try_ue(s: str):
    z = s.find("1")
    if z == -1:
        return ("invalid",) if len(s) > 31 else ("more",)
    total = 2 * z + 1
    if len(s) < total:
        return ("more",)
    suffix = s[z + 1 : total]
    return ("done", (1 << z) - 1 + (int(suffix, 2) if suffix else 0))


def _se(k: int) -> int:
    if k == 0:
        return 0
    return (k + 1) // 2 if (k & 1) else -(k // 2)


# --- byte-mask compilation --------------------------------------------------
def compile_byte_mask(auto: MbAutomaton, *, residual_only: bool = False) -> list:
    """bool[256]: which next emitted byte keeps the RBSP grammar legal, checked by
    chaining through element boundaries within the byte (strict). Caller ANDs Layer-1
    Annex-B on top. Uses a fresh overlay so lookahead nnz writes don't touch the grid.
    """
    mask = [False] * 256
    root = auto.clone()
    root.overlay = {} if auto.overlay is None else dict(auto.overlay)

    def visit(node, depth, prefix):
        for bit in (0, 1):
            child = node.clone()
            st = child.consume_bit(bit)
            if st == INVALID:
                continue
            nxt = (prefix << 1) | bit
            if depth + 1 == 8:
                mask[nxt] = True
            elif st == DONE:
                _fill(mask, nxt, depth + 1)
            elif (
                residual_only
                and child.stage == "slice"
                and child.ae_tag not in _RESIDUAL_TAGS
            ):
                # V1 decodes headers to maintain state but deliberately does not
                # constrain them. If a residual ends mid-byte, leave header bits in
                # the remainder permissive.
                _fill(mask, nxt, depth + 1)
            else:
                visit(child, depth + 1, nxt)

    visit(root, 0, 0)
    return mask


def _fill(mask, prefix, depth):
    """Mark every byte whose top `depth` bits are `prefix` as legal (remaining bits
    free). Used when the NAL ends mid-byte -- the rest is the next NAL's start code."""
    shift = 8 - depth
    base = prefix << shift
    for i in range(1 << shift):
        mask[base + i] = True
