"""Constrained-decoding mask for free-run H.264 byte generation.

Free-run stays valid only if every generated byte is a legal continuation; one
illegal byte ends the stream. Whether a byte is legal is not a model guess -- it
is computable from the H.264 grammar and the current parser state. So we compute
the legal set and mask the logits before sampling. This guarantees the stream
decodes; it does not make it match the ground truth.

Two constraints:
  Layer 1: Annex-B escaping. Byte lookback only, no parser. After 00 00 the next
           byte can't be 00/01/02 (would be a start code or unescaped emulation).
  Layer 2: CAVLC grammar. Ask the real parser: append the candidate byte, parse
           the current NAL, reject only on a real grammar error (ValueError/
           KeyError/IndexError). BitReaderError just means the field isn't done
           yet -- still legal. Cheap because one NAL is one macroblock here.

v1 masks VCL slice bytes only. SPS/PPS/SEI get Layer 1 only.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from litgpt.byte import h264_syntax as HS

START_CODE = (0, 0, 1)

# Parser exception kinds that mean "this byte is illegal". BitReaderError is
# excluded on purpose: it means the field isn't finished, not that it's wrong.
_ILLEGAL_KINDS = {"ValueError", "KeyError", "IndexError"}


@dataclass
class MaskState:
    """State the mask needs. Current-NAL bytes are rebuilt as we go; the SPS/PPS
    maps and nC grid are kept and only updated when a NAL closes.
    """

    # Parameter sets seen so far (usually arrive in the prefix).
    sps_map: dict[int, "HS.SPS"] = field(default_factory=dict)
    pps_map: dict[int, "HS.PPS"] = field(default_factory=dict)

    # Bytes of the open NAL, from its header byte on, no start code. Empty between NALs.
    cur_nal_bytes: bytearray = field(default_factory=bytearray)

    # True if the open NAL is a VCL slice (Layer 2 applies).
    cur_is_vcl: bool = False

    # Latched once the open slice reaches completion, so boundary stays True through
    # the trailing/start-code bytes (which accumulate in cur_nal_bytes before advance
    # sees the full start code). Reset when the NAL closes.
    cur_slice_complete: bool = False

    # nC neighbour grid from earlier macroblocks of the same picture. coeff_token's
    # legal set depends on it, and one MB is one NAL here, so it crosses NALs.
    nnz: "HS._NNZ | None" = None

    def last_two_raw(self) -> tuple[int, int] | None:
        if len(self.cur_nal_bytes) < 2:
            return None
        return self.cur_nal_bytes[-2], self.cur_nal_bytes[-1]


# --- Layer 1: Annex-B escaping ---------------------------------------------
def annexb_forbidden(state: MaskState, *, at_nal_boundary: bool) -> list[int]:
    """Bytes forbidden by Annex-B escaping given the last two raw bytes.

    Rule: only fires after 00 00.
      - mid-slice: forbid 00/01/02 (03 is the  just like "\", >=04 is fine).
      - slice done (at_nal_boundary): allow 00 and 01 so the next start code can be
        emitted; still forbid 02.
    `at_nal_boundary` comes from Layer 2 (slice parsed clean, past the stop bit).
    """
    if state.last_two_raw() == (0x00, 0x00):
        if at_nal_boundary:
            return [0x02]  # allow 00/01 so the next start code can be emitted
        else:
            return [0x00, 0x01, 0x02]
    return []


# --- Layer 2: CAVLC grammar via trial re-parse -----------------------------
def _trial_parse_is_legal(state: MaskState, candidate: int) -> bool:
    """True if appending `candidate` keeps the current VCL NAL grammar-legal.

    OK -> legal. Grammar error (_ILLEGAL_KINDS) -> illegal. BitReaderError /
    Unsupported -> field not finished, treat as legal.

    TODO(layer2):
      - buf = bytes(START_CODE) + cur_nal_bytes + bytes([candidate])
      - nal = HS.iter_nals(buf)[0]
      - res = HS.parse_nal(buf, nal, state.sps_map, state.pps_map, parse_slice_data=True)
      - return res.status == OK or res.reason_kind not in _ILLEGAL_KINDS

    TODO(nnz): parse_nal builds a fresh nC grid per NAL and can't see neighbours,
      so coeff_token's legal set is wrong at MB boundaries. Either:
        (a) thread state.nnz into the slice-data parse (touches the parser), or
        (b) v1: leave nC fresh -> mask is too permissive, never too strict.
    """

    trial_bytes = bytes(START_CODE) + state.cur_nal_bytes + bytes([candidate])
    nals = HS.iter_nals(trial_bytes)
    res = HS.parse_nal(
        trial_bytes, nals[0], state.sps_map, state.pps_map, parse_slice_data=True
    )
    if res.status == HS.ParseStatus.OK:
        return True

    if res.reason_kind in _ILLEGAL_KINDS:
        return False

    return True


# --- Slice-complete signal (on GENERATED bytes, no RBSP length) ------------
def _valid_trailing_bits(reader: "HS.BitReader") -> bool:
    """True if bits [reader.pos, nbits) are a valid rbsp_trailing_bits: one 1 bit
    then 0s to the byte boundary. Rejects >1 byte of trailing (extra zero bytes are
    not canonical) and the empty case (stop bit not emitted yet)."""
    n, pos = reader.nbits, reader.pos
    if pos >= n or n - pos > 8:
        return False

    def bit(p: int) -> int:
        return (reader.rbsp[p >> 3] >> (7 - (p & 7))) & 1

    if bit(pos) != 1:
        return False
    return all(bit(p) == 0 for p in range(pos + 1, n))


def _at_nal_boundary(state: MaskState, *, slice_max_mbs: int = 1) -> bool:
    """True if the open VCL slice is done on cur_nal_bytes so far.

    NOT via more_rbsp_data()/the stop bit -- that needs the RBSP length, which is
    set by the next start code we haven't generated. Detected structurally: parse
    the header + up to slice_max_mbs (==1 here) macroblocks, driving the loop by MB
    count instead of more_rbsp_data(), then require a valid rbsp_trailing_bits.
    Any BitReaderError => slice not finished => False.

    v1 uses a fresh nC grid (not state.nnz), so coeff_token lengths at MB boundaries
    can be slightly off -- see TODO(nnz).
    """
    nal_bytes = state.cur_nal_bytes
    if len(nal_bytes) < 2 or (nal_bytes[0] & 0x1F) not in HS.VCL_NAL_TYPES:
        return False
    rbsp, byte_map, _ = HS.unescape_rbsp(bytes(nal_bytes), 1, len(nal_bytes))
    if not byte_map:
        return False

    reader = HS.BitReader(rbsp)
    record = HS._Recorder(byte_map, len(rbsp))
    nal = HS.NALInfo(
        index=0,
        nal_type=nal_bytes[0] & 0x1F,
        ref_idc=(nal_bytes[0] >> 5) & 0x3,
        start_code_start=0,
        start_code_len=3,
        payload_start=0,
        payload_end=len(nal_bytes),
    )
    try:
        # Resolve sps/pps by peeking pps_id (mirrors _parse_slice).
        save = reader.pos
        reader.read_ue()  # first_mb
        reader.read_ue()  # slice_type
        pps = state.pps_map.get(reader.read_ue())
        reader.pos = save
        if pps is None:
            return False
        sps = state.sps_map.get(pps.sps_id)
        if sps is None:
            return False

        head = HS.parse_slice_header(reader, record, nal, sps, pps)
        if head.slice_type not in (HS.SLICE_TYPE_P, HS.SLICE_TYPE_I):
            return False
        nnz = HS._NNZ(sps.pic_width_in_mbs, sps.pic_height_in_mbs)  # v1: fresh grid
        curr = head.first_mb_in_slice
        target = curr + slice_max_mbs
        is_p = head.slice_type == HS.SLICE_TYPE_P
        while curr < target:
            if is_p:
                run = record.ue("mb_skip_run", reader, HS.Category.MB_HEADER, curr)
                curr += min(run, target - curr)  # skipped MBs
                if curr >= target:
                    break
            HS._parse_macroblock(reader, record, sps, pps, head, nnz, curr)
            curr += 1
    except HS.BitReaderError:
        return False  # slice not finished
    except (ValueError, KeyError, IndexError, HS._DesyncError, HS._Unsupported):
        return False  # illegal / can't confirm completion

    return _valid_trailing_bits(reader)


# --- The function the sampler calls ----------------------------------------
def get_valid_byte_mask(state: MaskState) -> list[bool]:
    """bool[256], True where the next byte keeps the stream decodable.

    Layer 1 always applies. Layer 2 (the expensive trial-parse) only runs inside an
    open, incomplete VCL slice -- once the slice is complete the only legal next
    bytes are the start code, which Layer 1 already allows. An all-False result is
    returned as-is; the rollout treats it as a desync and stops.
    """
    mask = [True] * 256

    # Slice done? -> only the start code follows (Layer 1 handles it, skip Layer 2).
    # Read the latched flag (maintained by advance) rather than re-parsing here; it
    # stays True through the trailing/start-code bytes. Non-VCL NALs get Layer 1 only
    # and aren't tracked, so treat them as "boundary" (allow the start code).
    boundary = state.cur_slice_complete if state.cur_is_vcl else True

    # Layer 1: Annex-B escaping.
    for b in annexb_forbidden(state, at_nal_boundary=boundary):
        mask[b] = False

    # Layer 2: CAVLC grammar, only mid-slice.
    if state.cur_is_vcl and state.cur_nal_bytes and not boundary:
        for b in range(256):
            if mask[b] and not _trial_parse_is_legal(state, b):
                mask[b] = False

    return mask


# --- State update: called after each accepted byte -------------------------
def _close_nal(state: MaskState, nal_payload: bytes) -> None:
    """Parse a finished NAL (header byte + payload, no start code) once, so any
    SPS/PPS it defines lands in state's maps for later slices.

    TODO(nnz): also roll the ending nC grid into state.nnz for the next VCL NAL.
    parse_nal builds the grid internally and discards it, so v1 leaves state.nnz
    None (fresh grid downstream).
    """
    if not nal_payload:
        return
    buf = bytes(START_CODE) + nal_payload
    nals = HS.iter_nals(buf)
    if nals:
        HS.parse_nal(buf, nals[0], state.sps_map, state.pps_map, parse_slice_data=True)


def advance(state: MaskState, byte: int) -> None:
    """Fold one accepted byte into MaskState. Most bytes just extend the open NAL;
    a completed start code closes the previous NAL and opens the next.
    """
    was_empty = len(state.cur_nal_bytes) == 0
    state.cur_nal_bytes.append(byte)
    if was_empty:
        # First byte of a new NAL is its header byte.
        state.cur_is_vcl = (byte & 0x1F) in HS.VCL_NAL_TYPES

    tail = state.cur_nal_bytes
    if len(tail) >= 3 and tuple(tail[-3:]) == START_CODE:
        sc_len = 4 if (len(tail) >= 4 and tuple(tail[-4:]) == (0, 0, 0, 1)) else 3
        _close_nal(state, bytes(tail[: len(tail) - sc_len]))
        state.cur_nal_bytes = bytearray()  # next NAL's header arrives on the next byte
        state.cur_is_vcl = False
        state.cur_slice_complete = False
        return

    # Latch slice completion once (stays set through trailing/start-code bytes). The
    # `not ...` short-circuits the parse away after it first fires.
    if state.cur_is_vcl and not state.cur_slice_complete and _at_nal_boundary(state):
        state.cur_slice_complete = True
