from pathlib import Path

import pytest
import torch

from litgpt.byte_mrt import (
    Candidate,
    MRTConfig,
    PreparedMRTStep,
    build_candidate_inputs,
    minimum_risk_coefficients,
    mrt_candidate_diagnostics,
    should_run_mrt,
    visual_risk,
)
from litgpt.data.byte_data import REGION_BRIDGE, SEQ_EOS_ID
from litgpt.eval.byte_reconstruction import ReconstructionSample


def make_sample() -> ReconstructionSample:
    return ReconstructionSample(
        h264_path=Path("unused.h264"),
        target_start=0,
        target_end=10,
        target_nal_index=1,
        frame_index=0,
        prompt_ids=torch.tensor([10, 11, 12]),
        prompt_region_ids=torch.tensor([1, 2, REGION_BRIDGE]),
        prompt_offset_ids=torch.tensor([0, 1, 5]),
        target_length=2,
        task="fim",
        replacement_start=5,
        replacement_end=7,
        generation_region_id=REGION_BRIDGE,
        generation_offset_start=6,
        stop_token=SEQ_EOS_ID,
    )


def test_mrt_schedule_runs_after_each_complete_interval():
    config = MRTConfig(interval=8, start_step=1000)

    assert not should_run_mrt(1000, config)  # The pretrained boundary itself is supervised only.
    assert not should_run_mrt(1007, config)  # Seven optimizer steps remain CE+EOS only.
    assert should_run_mrt(1008, config)  # The eighth optimizer step receives MRT.
    assert should_run_mrt(1016, config)  # The cadence repeats at the configured interval.


def test_mrt_length_modes_are_mutually_exclusive():
    config = MRTConfig(interval=1, oracle_length=True, learned_eos=True)

    with pytest.raises(ValueError, match="mutually exclusive"):
        config.validate()


def test_minimum_risk_coefficients_favor_lower_risk_candidates():
    scores = torch.tensor([-1.0, -1.0, -1.0])
    risks = torch.tensor([0.0, 1.0, 2.0])

    q, expected_risk, coefficients = minimum_risk_coefficients(scores, risks, 1.0)

    assert torch.allclose(q, torch.full((3,), 1 / 3))  # Equal model scores induce a uniform candidate distribution.
    assert torch.isclose(expected_risk, torch.tensor(1.0))  # Expected risk is computed under q.
    assert coefficients[0] < 0  # Gradient descent raises the score of the best candidate.
    assert coefficients[2] > 0  # Gradient descent lowers the score of the worst candidate.
    assert abs(float(coefficients.sum())) < 1e-6  # Centering removes a constant-risk baseline.


def test_smooth_mse_risk_preserves_order_without_hard_saturation():
    config = MRTConfig(risk_mode="smooth_mse", mse_tau=0.002)

    risks = [visual_risk(mse, config) for mse in (0.002, 0.01, 0.1)]

    assert risks[0] == 0.5  # Tau is the interpretable midpoint of the risk curve.
    assert risks[0] < risks[1] < risks[2] < 1.0  # Poor decoded candidates remain distinguishable.


def test_clipped_mse_risk_remains_available_for_reproducibility():
    config = MRTConfig(
        risk_mode="clipped_mse",
        mse_weight=1000.0,
        max_risk=2.0,
    )

    assert visual_risk(0.001, config) == 1.0  # Below-threshold behavior matches the original experiment.
    assert visual_risk(0.01, config) == 2.0  # The legacy mode still hard-clips large errors.


def test_minimum_risk_surrogate_matches_expected_risk_gradient():
    scores = torch.tensor([-0.7, -1.1, -1.8], requires_grad=True)
    risks = torch.tensor([0.1, 0.8, 1.7])
    alpha = 0.6
    direct_loss = (torch.softmax(alpha * scores, dim=0) * risks).sum()
    direct_gradient = torch.autograd.grad(direct_loss, scores)[0]

    _, _, coefficients = minimum_risk_coefficients(scores.detach(), risks, alpha)
    surrogate_gradient = torch.autograd.grad((coefficients * scores).sum(), scores)[0]

    assert torch.allclose(
        surrogate_gradient, direct_gradient
    )  # Per-candidate backward passes implement the exact MRT score gradient.


def test_candidate_inputs_align_first_byte_with_prompt_marker():
    sample = make_sample()
    candidate = Candidate(data=b"\x21\x22", stopped=True)

    inputs, labels = build_candidate_inputs(sample, candidate, torch.device("cpu"))

    assert inputs["idx"].tolist() == [[10, 11, 12, 0x21, 0x22]]  # Teacher forcing omits only the final EOS input.
    assert labels.tolist() == [[-100, -100, 0x21, 0x22, SEQ_EOS_ID]]  # The marker predicts the first generated byte.
    assert inputs["region_ids"].tolist() == [
        [1, 2, REGION_BRIDGE, REGION_BRIDGE, REGION_BRIDGE]
    ]  # Candidate inputs preserve the bridge region.
    assert inputs["offset_ids"].tolist() == [[0, 1, 5, 6, 7]]  # Generated inputs continue at the missing-span offsets.


def test_oracle_length_candidate_inputs_exclude_eos():
    sample = make_sample()
    candidate = Candidate(data=b"\x21\x22", stopped=False)

    inputs, labels = build_candidate_inputs(sample, candidate, torch.device("cpu"))

    assert inputs["idx"].tolist() == [[10, 11, 12, 0x21]]
    assert labels.tolist() == [[-100, -100, 0x21, 0x22]]
    assert SEQ_EOS_ID not in labels.tolist()[0]


def test_mrt_diagnostics_separate_ground_truth_from_sampled_candidates():
    candidates = (
        Candidate(data=b"gt", stopped=False, is_ground_truth=True),
        Candidate(data=b"a", stopped=False),
        Candidate(data=b"b", stopped=False),
    )
    prepared = PreparedMRTStep(
        sample=make_sample(),
        candidates=candidates,
        risks=torch.tensor([0.0, 0.6, 1.0]),
        candidate_mses=torch.tensor([0.0, 0.01, float("nan")]),
        candidate_scores=torch.tensor([-2.0, -2.5, -3.5]),
        candidate_decoded=torch.tensor([True, True, False]),
        candidate_probabilities=torch.tensor([0.5, 0.3, 0.2]),
        coefficients=torch.zeros(3),
        expected_risk=0.5,
        decode_rate=2 / 3,
        ground_truth_probability=0.5,
    )

    metrics = mrt_candidate_diagnostics(prepared)

    assert metrics["mrt/score_gt"] == -2.0  # GT score is selected by role, not position-dependent slicing.
    assert metrics["mrt/score_sampled_mean"] == -3.0  # Only model-generated candidate scores are averaged.
    assert metrics["mrt/score_margin_gt_vs_sampled"] == 1.0  # Positive margin means GT has higher mean log-probability.
    assert metrics["mrt/sampled_risk_mean"] == pytest.approx(0.8)  # GT's zero risk cannot create artificial sampled spread.
    assert metrics["mrt/sampled_risk_std"] == pytest.approx(0.2)  # Sampled-only spread measures reward discrimination.
    assert metrics["mrt/sampled_strict_decode_rate"] == 0.5  # Decode rate excludes the guaranteed-valid GT candidate.
    assert metrics["mrt/sampled_mse_mean"] == pytest.approx(0.01)  # Failed strict decodes are excluded from MSE statistics.
    assert metrics["mrt/sampled_q_sum"] == pytest.approx(0.5)
    assert metrics["mrt/sampled_q_mean"] == pytest.approx(0.25)
    assert metrics["mrt/sampled_q_max"] == pytest.approx(0.3)
    # sampled contribution = 0.3*0.6 + 0.2*1.0 = 0.38; expected_risk = sum is the same (GT risk = 0).
    assert metrics["mrt/sampled_expected_risk_contribution"] == pytest.approx(0.38)
    assert metrics["mrt/sampled_conditional_expected_risk"] == pytest.approx(0.38 / 0.5)


def test_mrt_diagnostics_without_ground_truth_candidate():
    candidates = (
        Candidate(data=b"a", stopped=False),
        Candidate(data=b"b", stopped=False),
        Candidate(data=b"c", stopped=False),
    )
    prepared = PreparedMRTStep(
        sample=make_sample(),
        candidates=candidates,
        risks=torch.tensor([0.2, 0.6, 1.0]),
        candidate_mses=torch.tensor([0.005, 0.02, float("nan")]),
        candidate_scores=torch.tensor([-2.5, -3.0, -3.5]),
        candidate_decoded=torch.tensor([True, True, False]),
        candidate_probabilities=torch.tensor([0.5, 0.3, 0.2]),
        coefficients=torch.zeros(3),
        expected_risk=0.48,
        decode_rate=2 / 3,
        ground_truth_probability=float("nan"),
    )

    metrics = mrt_candidate_diagnostics(prepared)

    # GT-specific metrics absent.
    assert "mrt/score_gt" not in metrics
    assert "mrt/score_margin_gt_vs_sampled" not in metrics
    # Sampled pool spans all candidates -> sums to 1, conditional == expected_risk.
    assert metrics["mrt/sampled_q_sum"] == pytest.approx(1.0)
    assert metrics["mrt/sampled_q_mean"] == pytest.approx(1.0 / 3)
    contribution = 0.5 * 0.2 + 0.3 * 0.6 + 0.2 * 1.0
    assert metrics["mrt/sampled_expected_risk_contribution"] == pytest.approx(contribution)
    assert metrics["mrt/sampled_conditional_expected_risk"] == pytest.approx(contribution)
