from pathlib import Path

import torch

from litgpt.byte_mrt import (
    Candidate,
    MRTConfig,
    build_candidate_inputs,
    minimum_risk_coefficients,
    should_run_mrt,
    visual_risk,
)
from litgpt.data.byte_data import REGION_BRIDGE, SEQ_EOS_ID
from litgpt.eval.byte_reconstruction import ReconstructionSample


def make_sample() -> ReconstructionSample:
    return ReconstructionSample(
        h264_path=Path("unused.h264"),
        target_start=0,
        target_end=10,
        target_nal_index=1,
        frame_index=0,
        prompt_ids=torch.tensor([10, 11, 12]),
        prompt_region_ids=torch.tensor([1, 2, REGION_BRIDGE]),
        prompt_offset_ids=torch.tensor([0, 1, 5]),
        target_length=2,
        task="fim",
        replacement_start=5,
        replacement_end=7,
        generation_region_id=REGION_BRIDGE,
        generation_offset_start=6,
        stop_token=SEQ_EOS_ID,
    )


def test_mrt_schedule_runs_after_each_complete_interval():
    config = MRTConfig(interval=8, start_step=1000)

    assert not should_run_mrt(1000, config)  # The pretrained boundary itself is supervised only.
    assert not should_run_mrt(1007, config)  # Seven optimizer steps remain CE+EOS only.
    assert should_run_mrt(1008, config)  # The eighth optimizer step receives MRT.
    assert should_run_mrt(1016, config)  # The cadence repeats at the configured interval.


def test_minimum_risk_coefficients_favor_lower_risk_candidates():
    scores = torch.tensor([-1.0, -1.0, -1.0])
    risks = torch.tensor([0.0, 1.0, 2.0])

    q, expected_risk, coefficients = minimum_risk_coefficients(scores, risks, 1.0)

    assert torch.allclose(q, torch.full((3,), 1 / 3))  # Equal model scores induce a uniform candidate distribution.
    assert torch.isclose(expected_risk, torch.tensor(1.0))  # Expected risk is computed under q.
    assert coefficients[0] < 0  # Gradient descent raises the score of the best candidate.
    assert coefficients[2] > 0  # Gradient descent lowers the score of the worst candidate.
    assert abs(float(coefficients.sum())) < 1e-6  # Centering removes a constant-risk baseline.


def test_smooth_mse_risk_preserves_order_without_hard_saturation():
    config = MRTConfig(risk_mode="smooth_mse", mse_tau=0.002)

    risks = [visual_risk(mse, config) for mse in (0.002, 0.01, 0.1)]

    assert risks[0] == 0.5  # Tau is the interpretable midpoint of the risk curve.
    assert risks[0] < risks[1] < risks[2] < 1.0  # Poor decoded candidates remain distinguishable.


def test_clipped_mse_risk_remains_available_for_reproducibility():
    config = MRTConfig(
        risk_mode="clipped_mse",
        mse_weight=1000.0,
        max_risk=2.0,
    )

    assert visual_risk(0.001, config) == 1.0  # Below-threshold behavior matches the original experiment.
    assert visual_risk(0.01, config) == 2.0  # The legacy mode still hard-clips large errors.


def test_minimum_risk_surrogate_matches_expected_risk_gradient():
    scores = torch.tensor([-0.7, -1.1, -1.8], requires_grad=True)
    risks = torch.tensor([0.1, 0.8, 1.7])
    alpha = 0.6
    direct_loss = (torch.softmax(alpha * scores, dim=0) * risks).sum()
    direct_gradient = torch.autograd.grad(direct_loss, scores)[0]

    _, _, coefficients = minimum_risk_coefficients(scores.detach(), risks, alpha)
    surrogate_gradient = torch.autograd.grad((coefficients * scores).sum(), scores)[0]

    assert torch.allclose(
        surrogate_gradient, direct_gradient
    )  # Per-candidate backward passes implement the exact MRT score gradient.


def test_candidate_inputs_align_first_byte_with_prompt_marker():
    sample = make_sample()
    candidate = Candidate(data=b"\x21\x22", stopped=True)

    inputs, labels = build_candidate_inputs(sample, candidate, torch.device("cpu"))

    assert inputs["idx"].tolist() == [[10, 11, 12, 0x21, 0x22]]  # Teacher forcing omits only the final EOS input.
    assert labels.tolist() == [[-100, -100, 0x21, 0x22, SEQ_EOS_ID]]  # The marker predicts the first generated byte.
    assert inputs["region_ids"].tolist() == [
        [1, 2, REGION_BRIDGE, REGION_BRIDGE, REGION_BRIDGE]
    ]  # Candidate inputs preserve the bridge region.
    assert inputs["offset_ids"].tolist() == [[0, 1, 5, 6, 7]]  # Generated inputs continue at the missing-span offsets.
