from dataclasses import dataclass

import torch

from litgpt.byte import grpo
from litgpt.byte.data import SEQ_EOS_ID
from litgpt.byte.megabyte_inference import GeneratedCandidate
from litgpt.byte.reconstruction import ReconstructionSample


def _sample(path) -> ReconstructionSample:
    return ReconstructionSample(
        h264_path=path,
        target_start=0,
        target_end=3,
        target_nal_index=0,
        frame_index=0,
        prompt_ids=torch.tensor([1]),
        prompt_region_ids=torch.tensor([0]),
        prompt_offset_ids=torch.tensor([0]),
        target_length=1,
        task="fim",
        replacement_start=1,
        replacement_end=2,
    )


def test_fim_stop_states_require_positive_before_adding_negatives(tmp_path, monkeypatch):
    path = tmp_path / "sample.h264"
    path.write_bytes(b"\xaa\xff\xbb")

    @dataclass
    class FakeState:
        slice_max_mbs: int | None
        fail_closed: bool
        position: int = 0
        automaton_unknown: bool = False
        generation_started: bool = False

    monkeypatch.setattr(grpo.HM, "MaskState", FakeState)
    monkeypatch.setattr(grpo.HM, "slice_max_mbs_for_layout", lambda _: 1)
    monkeypatch.setattr(grpo.HM, "get_valid_byte_mask", lambda state: [True] * 256)
    monkeypatch.setattr(
        grpo.HM, "advance", lambda state, byte: setattr(state, "position", state.position + 1)
    )
    monkeypatch.setattr(
        grpo.HM,
        "can_append_bytes",
        lambda state, suffix, require_complete: state.position == 3,
    )

    states = grpo.fim_stop_states(
        _sample(path),
        [GeneratedCandidate(data=b"\x01\x02", stopped=False)],
        slice_layout="macroblock",
        negative_samples=2,
        max_positive_states=1,
    )
    assert [(state.prefix_length, state.should_stop) for state in states] == [
        (2, True),
        (1, False),
        (0, False),
    ]

    no_positive = grpo.fim_stop_states(
        _sample(path),
        [GeneratedCandidate(data=b"\x01", stopped=True)],
        slice_layout="macroblock",
        negative_samples=2,
        max_positive_states=1,
    )
    assert no_positive == []

    # A forbidden generated byte must fail closed without indexing an empty
    # retained-state buffer.
    monkeypatch.setattr(grpo.HM, "get_valid_byte_mask", lambda state: [False] * 256)
    parser_invalid = grpo.fim_stop_states(
        _sample(path),
        [GeneratedCandidate(data=b"\x01\x02\x03", stopped=False)],
        slice_layout="macroblock",
        negative_samples=1,
        max_positive_states=1,
    )
    assert parser_invalid == []


def test_balanced_stop_loss_moves_positive_and_negative_eos_oppositely():
    logits = torch.tensor([-1.0, -1.0, 1.0], requires_grad=True)
    gathered = torch.log(torch.sigmoid(logits)).view(3, 1, 1)
    labels = torch.full((3, 1, 1), SEQ_EOS_ID, dtype=torch.long)
    supervised = torch.ones((3, 1, 1), dtype=torch.bool)
    should_stop = torch.tensor([True, False, False])

    loss, metrics = grpo.fim_stop_loss(
        gathered, labels, supervised, should_stop
    )
    loss.backward()

    assert logits.grad is not None
    assert logits.grad[0] < 0  # gradient descent raises positive-state EOS
    assert bool((logits.grad[1:] > 0).all())  # and lowers negative-state EOS
    assert metrics["grpo/stop_positive_states"] == 1
    assert metrics["grpo/stop_negative_states"] == 2


def test_ground_truth_reconnection_is_required_for_parser_labels(tmp_path, monkeypatch):
    path = tmp_path / "sample.h264"
    path.write_bytes(b"\xaa\xff\xbb")

    @dataclass
    class FakeState:
        slice_max_mbs: int | None
        fail_closed: bool
        position: int = 0
        automaton_unknown: bool = False
        generation_started: bool = False

    monkeypatch.setattr(grpo.HM, "MaskState", FakeState)
    monkeypatch.setattr(grpo.HM, "slice_max_mbs_for_layout", lambda _: 1)
    monkeypatch.setattr(
        grpo.HM, "advance", lambda state, byte: setattr(state, "position", state.position + 1)
    )
    monkeypatch.setattr(grpo.HM, "get_valid_byte_mask", lambda state: [True] * 256)
    monkeypatch.setattr(
        grpo.HM,
        "can_append_bytes",
        lambda state, suffix, require_complete: state.position == 2 and suffix == b"\xbb",
    )

    assert grpo.fim_ground_truth_reconnects(
        _sample(path), slice_layout="macroblock"
    )

    monkeypatch.setattr(grpo.HM, "get_valid_byte_mask", lambda state: [False] * 256)
    assert not grpo.fim_ground_truth_reconnects(
        _sample(path), slice_layout="macroblock"
    )


def test_stop_loss_requires_learned_eos():
    config = grpo.GRPOConfig(
        interval=1,
        learned_eos=False,
        stop_loss_weight=1.0,
    )
    try:
        config.validate()
    except ValueError as exc:
        assert "learned-EOS" in str(exc)
    else:
        raise AssertionError("expected stop-loss configuration validation to fail")
